version: "3.7"
services:

  lb:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway
    ports:
      - "8080:80"
    depends_on:
      - swagger-ui.local
      - portal-service.local
    environment:
      RESOLVER_ADDR: 127.0.0.11

  "portal-service.local":
    build: ./spa-portal
    image: spa-portal

  "swagger-ui.local":
    image:  swaggerapi/swagger-ui
    environment:
      URLS: "[ { url: \"./docs/auth-api.yml\", name: \"Auth\" }, { url: \"./docs/recommendations-api.yml\", name: \"Recommendations\" },{ url: \"./docs/books-api.yml\", name: \"Books\" },]"
    volumes:
      - ./api-docs:/usr/share/nginx/html/docs

#  swagger-editor:
#    image:  swaggerapi/swagger-editor
#    ports:
#      - "8889:8080"
#    environment:
#      - SWAGGER_JSON=/docs/books-api.json
#    volumes:
#      - ./api-docs:/docs